apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-apgs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0003-tenant/tkrw-pr714-0075-0003-app/devfile-sample-apgs@sha256:1fd87692cfde8141a247f4ebd1c2851a383e87f8fd18749230bd8c82f439b34a
        name: my-nodejs
        resources: {}
status: {}
